resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BinaryLoggerArgs: '"/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  DotNetCoreVersion: '3.1.100'
  SignType: 'Test'

trigger:
  batch: true
  branches:
    include:
    - 'master'
    - 'refs/tags/*'
  paths:
    exclude:
    - '*.md'

pr: none

stages:
- stage:
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      name: VSEng-MicroBuildVS2019
    steps:
    - script: 'echo ##vso[task.setvariable variable=SignType;]Real'
      displayName: 'Set SignType to Real for tagged commits'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

    - task: UseDotNet@2
      displayName: 'Install .NET Core $(DotNetCoreVersion)'
      inputs:
        version: '$(DotNetCoreVersion)'

    - task: MicroBuildSigningPlugin@1
      displayName: 'Install MicroBuild Signing Plugin'
      inputs:
        signType: '$(SignType)'
        zipSources: false

    - task: MSBuild@1
      displayName: 'Build Solution'
      inputs:
        solution: SlnGen.sln
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '$(BinaryLoggerArgs)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(ArtifactsDirectoryName)'
        ArtifactName: $(ArtifactsDirectoryName)
      condition: always()

- stage:
  displayName: 'Deploy'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  jobs:
  - deployment: 'NuGet'
    displayName: 'Publish NuGet Packages'
    pool:
      vmImage: 'windows-latest'
    environment: 'SlnGen-NuGet'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetCommand@2
            displayName: 'Push NuGet Package'
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/$(ArtifactsDirectoryName)/**/Microsoft.VisualStudio.SlnGen*.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'NuGet-1ES-Full'
